name: bi-monthly Android App Deploy

on:
  workflow_dispatch:  # Manual trigger
      inputs:
        upload_releases:
          description: 'Upload releases'
          required: true
          default: 'true'
          type: boolean
        mark_prerelease:
          description: 'Mark as prerelease'
          required: true
          default: 'false'
          type: boolean
      

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'corretto'
  BUILD_GRADLE_PATH: 'app/build.gradle'  # Adjust path if necessary

jobs:
  prepare-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      old_version_name: ${{ steps.version.outputs.old_version_name }}
      version_name: ${{ steps.version.outputs.version_name }}
      base_version_code: ${{ steps.version.outputs.version_code }}
    env:
        UPLOAD_RELEASES: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.upload_releases || 'false' }}
        MARK_PRERELEASE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.mark_prerelease || 'false' }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - id: version
        run: |
          OLD_VERSION_CODE=$(grep "versionCode" $BUILD_GRADLE_PATH | head -1 | grep -oE '[0-9]+')
          OLD_VERSION_NAME=$(grep "versionName" $BUILD_GRADLE_PATH | head -1 | grep -oE '"([^"]+)"' | tr -d '"')
          
          NEW_VERSION_CODE=$((OLD_VERSION_CODE + 10))
          
          IFS='.' read -ra VERSION_PARTS <<< "$OLD_VERSION_NAME"
          MINOR=$((VERSION_PARTS[2] + 1))
          VERSION_PARTS[2]=$MINOR
          NEW_VERSION_NAME="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"

          echo "old_version_name=$OLD_VERSION_NAME" >> $GITHUB_OUTPUT
          echo "version_name=$NEW_VERSION_NAME" >> $GITHUB_OUTPUT
          echo "version_code=$NEW_VERSION_CODE" >> $GITHUB_OUTPUT
          echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

          # Update build.gradle
          sed -i "s/versionCode $OLD_VERSION_CODE/versionCode $NEW_VERSION_CODE/" $BUILD_GRADLE_PATH
          sed -i "s/versionName \"$OLD_VERSION_NAME\"/versionName \"$NEW_VERSION_NAME\"/" $BUILD_GRADLE_PATH

          echo "VERSION_NAME=$NEW_VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$NEW_VERSION_CODE" >> $GITHUB_ENV

          # Commit and push version update
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add $BUILD_GRADLE_PATH
          git commit -m "Bump version to $NEW_VERSION_NAME (code: $NEW_VERSION_CODE) [skip ci]" || echo "No changes to commit"
          git push --force

  build-and-release:
    needs: prepare-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Update Version Code and Version Name for Architecture
        run: |
          ARCH_VERSION_CODE=${{needs.prepare-version.outputs.base_version_code}}
          sed -i "s/versionCode [0-9]*/versionCode $ARCH_VERSION_CODE/" $BUILD_GRADLE_PATH
          sed -i "s/versionName \"${{needs.prepare-version.outputs.old_version_name}}\"/versionName \"${{needs.prepare-version.outputs.version_name}}\"/" $BUILD_GRADLE_PATH
          
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > release.keystore

      - name: Build APK for
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$PWD/release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Prepare APK
        run: |
          mkdir -p artifacts
          find app/build/outputs/apk/release/ -name "*-release.apk" -exec cp {} artifacts/clauncher-${{ needs.prepare-version.outputs.version_name }}.apk \;

      - name: Upload to Release
        # if: github.event_name == 'workflow_dispatch' && env.UPLOAD_RELEASES == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/clauncher-${{ needs.prepare-version.outputs.version_name }}.apk
          name: "CLauncher ${{ needs.prepare-version.outputs.version_name }}"
          tag_name: "${{ needs.prepare-version.outputs.version_name }}"
          prerelease: ${{ env.MARK_PRERELEASE }}
          fail_on_unmatched_files: false
          body: |
            ## CLauncher Release ${{ needs.prepare-version.outputs.version_name }}
            
            **Build Date**: ${{ needs.prepare-version.outputs.BUILD_DATE }}
            **Base Version Code**: ${{ needs.prepare-version.outputs.base_version_code }}
            
          generate_release_notes: true

      - name: Log build.gradle
        run: cat $BUILD_GRADLE_PATH
