name: Dependabot auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{secrets.GH_TOKEN}}
          merge-method: squash
          target: minor
